### ISSUE TITLE
How easy would it be to run MicroPython on the KeyBow 2040?

### ISSUE THREAD

**Issue by rtyley** [pimoroni/pmk-circuitpython#6]
Unfortunately some of the differences between CircuitPython and MicroPython are a bit limiting for me - for example the `time` module is quite constrained ([CircuitPython](https://docs.circuitpython.org/en/latest/shared-bindings/time/index.html) vs [MicroPython](https://docs.micropython.org/en/latest/library/time.html)). I don't need USB-HID support for my project, so how easy would it be to run MicroPython on it instead?

There's [no specific build of Micropython](https://micropython.org/download/?vendor=Pimoroni) for the KeyBow 2040, so far as I can see:

![image](https://user-images.githubusercontent.com/52038/158626211-3e4157d1-cca6-43ca-b4e6-92047a16f3bc.png)

Would it be safe for me to use the standard [`rp2-pico`](https://micropython.org/download/rp2-pico/) build instead?

**Comment by Gadgetoid** [comment]
You can also peer into the depths of CircuitPython to figure out which pin goes to which key:

https://github.com/adafruit/circuitpython/blob/af9f80daebfd6a5a4a069070d439dce242581df5/ports/raspberrypi/boards/pimoroni_keybow2040/pins.c#L16-L31

**Comment by rtyley** [comment]
> You can also peer into the depths of CircuitPython to figure out which pin goes to which key

Ah, thank you!
